In [2]:
import os

In [10]:
subsets = {"rsna-pulmonary-embolism": 5, "chexpert": 20, "CC-CCII": 20, "ssim-covid19": 50, "lung-pet-ct-dx": 20}

base_command = """CUDA_LAUNCH_BLOCKING=1 python train_experts.py \
--backbone biomedclip \
--batch_size 128 \
--blr 2e-4 \
--residual_scale 0.6 \
--epochs {} \
--warmup_epochs {} \
--weight_decay 0.05 \
--drop_path 0.1 \
--reprob 0.25 \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--subsets {} \
--input_size 224 \
--data_root /research/d5/gds/yzhong22/datasets/multitask-moe \
--output_dir /research/d5/gds/yzhong22/experiments/multitask-moe \
--use_amp True"""

commands = []
for subset, epoch in subsets.items():
    commands.append(base_command.format(epoch, epoch // 5, subset))

# print("&&".join(commands[3:5]))

# print("&&".join(commands[2:3] + commands[5:6]))
print("&&".join(commands[1]))

CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 5 --warmup_epochs 1 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets rsna-pulmonary-embolism --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True


In [13]:
subsets = {
    "rsna-pulmonary-embolism": 5,
    "chexpert-cardiomegaly": 20,
    "chexpert-edema": 20,
    "chexpert-pleural\ effusion": 20,
    "chexpert-consolidation": 20,
    "chexpert-pneumonia": 20,
    "chexpert-atelectasis": 20,
    "chexpert-pneumothorax": 20,
    "CC-CCII": 20,
    "ssim-covid19": 50,
    "lung-pet-ct-dx": 20,
}

base_command = """CUDA_LAUNCH_BLOCKING=1 python train_experts.py \
--backbone biomedclip \
--batch_size 128 \
--blr 2e-4 \
--residual_scale 0.6 \
--epochs {} \
--warmup_epochs {} \
--weight_decay 0.05 \
--drop_path 0.1 \
--reprob 0.25 \
--mixup 0.8 \
--cutmix 1.0 \
--smoothing 0.1 \
--subsets {} \
--input_size 224 \
--data_root /research/d5/gds/yzhong22/datasets/multitask-moe \
--output_dir /research/d5/gds/yzhong22/experiments/multitask-moe \
--use_amp True"""

commands = []
for subset, epoch in subsets.items():
    commands.append(base_command.format(epoch, epoch // 5, subset))

print("&&".join(commands[1:8]))

CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-cardiomegaly --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-edema --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4

CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-cardiomegaly --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-edema --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-pleural\ effusion --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-consolidation --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-pneumonia --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-atelectasis --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True&&CUDA_LAUNCH_BLOCKING=1 python train_experts.py --backbone biomedclip --batch_size 128 --blr 2e-4 --residual_scale 0.6 --epochs 20 --warmup_epochs 4 --weight_decay 0.05 --drop_path 0.1 --reprob 0.25 --mixup 0.8 --cutmix 1.0 --smoothing 0.1 --subsets chexpert-pneumothorax --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --output_dir /research/d5/gds/yzhong22/experiments/multitask-moe --use_amp True


In [8]:
",".join(subsets.keys())

'rsna-pulmonary-embolism,chexpert-cardiomegaly,chexpert-edema,chexpert-pleural\\ effusion,chexpert-consolidation,chexpert-pneumonia,chexpert-atelectasis,chexpert-pneumothorax,CC-CCII,ssim-covid19,lung-pet-ct-dx'

## eval

In [17]:
# stage 1

subsets = [
    "rsna-pulmonary-embolism",
    "chexpert-cardiomegaly",
    "chexpert-edema",
    "chexpert-pleural\\ effusion",
    "chexpert-consolidation",
    "chexpert-pneumonia",
    "chexpert-atelectasis",
    "chexpert-pneumothorax",
    "CC-CCII",
    "ssim-covid19",
    "lung-pet-ct-dx",
]


base_command = """CUDA_LAUNCH_BLOCKING=1 python eval_adaptation.py \
--backbone biomedclip \
--batch_size 128 \
--residual_scale 0.6 \
--experts {} \
--eval_subsets rsna-pulmonary-embolism,chexpert,CC-CCII,ssim-covid19,lung-pet-ct-dx \
--ckpt_dir /research/d5/gds/yzhong22/experiments/multitask-moe/biomedclip/seed0/lp \
--input_size 224 \
--data_root /research/d5/gds/yzhong22/datasets/multitask-moe \
--save_pred True \
--use_amp True"""


commands = []
for subset in subsets:
    commands.append(base_command.format(subset))

print("&&".join(commands[-1:]))

CUDA_LAUNCH_BLOCKING=1 python eval_adaptation.py --backbone biomedclip --batch_size 128 --residual_scale 0.6 --experts lung-pet-ct-dx --eval_subsets rsna-pulmonary-embolism,chexpert,CC-CCII,ssim-covid19,lung-pet-ct-dx --ckpt_dir /research/d5/gds/yzhong22/experiments/multitask-moe/biomedclip/seed0/lp --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --save_pred True --use_amp True


['rsna-pulmonary-embolism', 'chexpert-cardiomegaly', 'chexpert-edema', 'chexpert-pleural\\ effusion', 'chexpert-consolidation', 'chexpert-pneumonia', 'chexpert-atelectasis', 'chexpert-pneumothorax', 'CC-CCII', 'ssim-covid19', 'lung-pet-ct-dx']


CUDA_LAUNCH_BLOCKING=1 python eval_adaptation.py --backbone biomedclip --batch_size 128 --residual_scale 0.6 --experts chexpert-edema --eval_subsets chexpert --ckpt_dir /research/d5/gds/yzhong22/experiments/multitask-moe/biomedclip/seed0/lp --input_size 224 --data_root /research/d5/gds/yzhong22/datasets/multitask-moe --save_pred True --use_amp True
